modLoader="javafml" #mandatory
loaderVersion="[26,)" #mandatory (26 is current forge version)
credits="Thanks for Tinicraft goes to Java and Harry Talks" #optional
authors="Tini1212" #optional

[[mods]] #mandatory
modId="tinicraft" #mandatory
version="0.1" #mandatory
displayName="Tini Craft" #mandatory
description='''
This mod is a small starter mod :).
'''

[[dependencies.tinicraft]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[27,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.tinicraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"